### ISSUE TITLE
关于拍照按钮

### ISSUE THREAD

**Issue by Cesaradu** [aiyaapp/AiyaEffectsIOS#12]
Demo里AiyaCamera这个类，我看了属性和方法，没有拍照相关的，请问我要拍照的话怎么处理？

**Comment by WangYng** [comment]
相机回调的CVPixelBuffer可以转换成UIImage

**Comment by WangYng** [comment]
- (UIImage *)image{
#if TARGET_IPHONE_SIMULATOR || TARGET_OS_IPHONE

    CVPixelBufferLockBaseAddress(renderTarget, 0);
    
    //从 CVImageBufferRef 取得影像的细部信息
    uint8_t *base;
    size_t width, height, bytesPerRow;
    base = CVPixelBufferGetBaseAddress(renderTarget);
    width = CVPixelBufferGetWidth(renderTarget);
    height = CVPixelBufferGetHeight(renderTarget);
    bytesPerRow = CVPixelBufferGetBytesPerRow(renderTarget);
    
    //利用取得影像细部信息格式化 CGContextRef
    CGColorSpaceRef colorSpace;
    CGContextRef cgContext;
    colorSpace = CGColorSpaceCreateDeviceRGB();
    cgContext = CGBitmapContextCreate(base, width, height, 8, bytesPerRow, colorSpace, kCGBitmapByteOrder32Little | kCGImageAlphaPremultipliedFirst);
    CGColorSpaceRelease(colorSpace);
    
    //透过 CGImageRef 将 CGContextRef 转换成 UIImage
    CGImageRef cgImage;
    UIImage *image;
    cgImage = CGBitmapContextCreateImage(cgContext);
    image = [UIImage imageWithCGImage:cgImage];
    CGImageRelease(cgImage);
    CGContextRelease(cgContext);
    
    CVPixelBufferUnlockBaseAddress(renderTarget, 0);
    
    //成功转换成 UIImage
    return image;
#else
    return NULL;
#endif
}

**Comment by Cesaradu** [comment]
谢谢
