### ISSUE TITLE
[ERROR] glGetUniformLocation: ERROR: type not actived, ProgramID 36

### ISSUE THREAD

**Issue by jasminpsimform** [aiyaapp/AiyaEffectsIOS#38]
Thanks for the great library.

/Users/sunbo/Downloads/visual-effect-sdk/src/Shader2.cpp/SetUniform1i:251 [ERROR] glGetUniformLocation: ERROR: type not actived, ProgramID 36

getting this kind of warning while use "nationalFlag" named filter.

and sometime crashed with "AiyaEffectSDK was compiled with optimization - stepping may behave oddly; variables may not be available."

Any help would be appreciated.

Again thanks for this library.

**Comment by WangYng** [comment]
Sorry for the late reply.

1. "nationalFlag" . We will solve this problem in this week.
2. crashed . You can try debug mode run.

Let me know if you have any questions or concerns.
