### ISSUE TITLE
你好，申请下来的appkey运行提示无效，而且开发文档不是iOS的，贴图制作也没有文档

### ISSUE THREAD

**Issue by gongsunqingyang** [aiyaapp/AiyaEffectsIOS#7]
[DYMTLInitPlatform] platform initialization successful
- License key file not found or corrupt.
- You don't have a valid license for visage|SDK FaceTrack. Please contact your sales representative. (Error code 0x00000010)

Face tracking will work, but it will stop after one minute.

**Comment by WangYng** [comment]
您好.1. 对于appkey无效.请使用我们最新的SDK版本. 2. 开发文档不是iOS的?这个不是很理解. 3. 贴图制作文档正在编辑中.目前可以联系我们直接向我们索要

**Comment by gongsunqingyang** [comment]
您好，iOS开发文档我已经找到了，贴图制作文档我向客服索要了一份。我还有一些问题，贴图制作文档里面描述的和Demo中的资源类型有些不一致。比如在文档中，3D obj模型是以源文件形式存放在某一文件夹中，而在Demo中却是以.zip格式存放在某一文件夹中，当解压后里面是若干.arf文件。如图：

（文档）
![qq20170608-164758](https://user-images.githubusercontent.com/13862075/26920038-44724e7e-4c6a-11e7-89ed-7e44f3d50cdf.png)
（Demo）
![qq20170608-164908](https://user-images.githubusercontent.com/13862075/26920106-71eea49c-4c6a-11e7-89df-7e9474e52329.png) 

1.我在网上找了许多工具都无法打开.arf文件，请问这种文件是怎么生成的？
2.对于这种不一致，我是应该遵循文档还是参照Demo来写？
3.您能把最新的贴图制作文档给我一份么? 657582138@qq.com

**Comment by WangYng** [comment]
贴图制作教程还没有很完善...和相应的SDK没有对应上..正在修改中

**Comment by WangYng** [comment]
贴图制作教程已经有了.可以通过以下方式联系客服获取
客服QQ：2058288593
联系电话：18676907096
邮箱：marketing@aiyaapp.com
